name: E2E
on:
  pull_request:
    types: [labeled, synchronize, opened]
  workflow_dispatch:
jobs:
  e2e:
    if: contains(github.event.pull_request.labels.*.name, 'e2e') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Start dev server
        run: npm run dev &
      - name: Wait on dev server
        run: npx wait-on http://localhost:5173
      - name: Run E2E
        run: npm run e2e
      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
